// Generated by CoffeeScript 1.4.0
/*
 GET home page.
*/

exports.index = function(req, res) {
  if (req.params.id) {
    return res.render(req.params.id, {
      slideId: req.params.id
    });
  } else {
    return res.render('index', {
      slideId: 'default'
    });
  }
};
